---
title: "Scenario A | Comparison"
format: 
  html:
    toc: true
    code-fold: true
    embed-resources: true
editor: visual
execute: 
  warning: false
lightbox: true  
---

# Setup

Load libraries:

```{r load-libraries}
library(tidyverse)
library(ggpubr)
library(knitr)
```

Load in results from Extinct and Extant simulations:

```{r load-results}
predictions_extinct <- readRDS("Outputs/A/Extinct/predictions.rds")
predictions_extant <- readRDS("Outputs/A/Extant/predictions.rds")

thresholds <- readRDS("Outputs/A/Extinct/thresholds.rds")
error_rates <- readRDS("Outputs/A/Extant/error_rates.rds")
```

Specify "ideal" values for thresholds and error rates:

```{r ideal-values}
ideal_threshold <- c(100, 125)
ideal_errorrate <- c(0, 0.1)
```

Re-specify relevant parameters used in simulations:

```{r parameters}
extinction_time <- 100
test_time <- 100
beta <- 0.2
```

# Comparison

```{r comparison}
#| fig-dpi: 600
#| fig-width: 9
#| fig-height: 3
scenario_a <- left_join(thresholds, error_rates, by = "model")

new_models <- c("BA26B1", "BA26B2", "BA26B3", "BA26B4")

best_models <- scenario_a %>%
  filter(threshold < 125, error_rate < 0.1) %>%
  pull(model)

saveRDS(best_models, "Outputs/A/best_models.rds")

predictions_extinct <- predictions_extinct %>%
  mutate(model_class = case_when(
    model %in% new_models ~ "New",
    model %notin% new_models & model %in% best_models ~ "Best",
    model %notin% new_models & model %notin% best_models ~ "Old"
  ))
predictions_extant <- predictions_extant %>%
  mutate(model_class = case_when(
    model %in% new_models ~ "New",
    model %notin% new_models & model %in% best_models ~ "Best",
    model %notin% new_models & model %notin% best_models ~ "Old"
  ))

scenario_a <- scenario_a %>%
  mutate(model_class = case_when(
    model %in% new_models ~ "New",
    model %notin% new_models & model %in% best_models ~ "Best",
    model %notin% new_models & model %notin% best_models ~ "Old"
  ))

print(length(best_models))

best_models <- paste0("- ", best_models, collapse = "\n")

header <- paste0(
  "Models with power threshold < ", ideal_threshold[2],
  " and Type I error rate < ", ideal_errorrate[2], ":"
)

asis_output(paste0(header, "\n\n```text\n", best_models, "\n```"))

extinct_plot <- ggplot() +
  geom_line(
    data = predictions_extinct,
    aes(
      x = test_time, y = fit,
      group = model, colour = model_class, alpha = model_class
    ),
    linewidth = 1
  ) +
  geom_hline(yintercept = 1 - beta, linetype = "dashed") +
  scale_x_continuous(
    limits = c(extinction_time, extinction_time * 2),
    breaks = seq(extinction_time, extinction_time * 2,
      by = extinction_time / 4
    ),
    expand = expansion(mult = c(0.05, 0.1))
  ) +
  scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) +
  scale_size_continuous(range = c(0, 1)) +
  scale_colour_manual(values = c(
    "New" = "blue", "Best" = "green3", "Old" = "black")
  ) +
  scale_alpha_manual(values = c(
    "New" = 1, "Best" = 0.1, "Old" = 0.1)
  ) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(
    title = "A) Extinct",
    x = paste0("Test Time\n(Extinction = ", extinction_time, ")"),
    y = "Power"
  )

extant_plot <- ggplot() +
  geom_line(
    data = predictions_extant,
    aes(
      x = last_time, y = fit,
      group = model, colour = model_class, alpha = model_class
    ),
    linewidth = 1
  ) +
  scale_x_continuous(
    limits = c(extinction_time * 0.5, extinction_time),
    breaks = seq(extinction_time * 0.5, extinction_time,
      by = extinction_time / 10
    ),
    expand = expansion(mult = c(0.05, 0.1))
  ) +
  scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) +
  scale_size_continuous(range = c(0, 1)) +
  scale_colour_manual(values = c(
    "New" = "blue", "Best" = "green3", "Old" = "black")
  ) +
  scale_alpha_manual(values = c(
    "New" = 1, "Best" = 0.1, "Old" = 0.1)
  ) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(
    title = "B) Extant",
    x = paste0("Time of Last Sighting\n(Test Time = ", test_time, ")"),
    y = "Type I Error Rate"
  )

comparison_plot <- ggplot(scenario_a) +
  annotate(
    "rect",
    xmin = ideal_threshold[1], xmax = ideal_threshold[2],
    ymin = ideal_errorrate[1], ymax = ideal_errorrate[2],
    colour = "green3", fill = NA
  ) +
  geom_point(
    aes(x = threshold, y = error_rate, colour = model_class, alpha = model_class),
    size = 2
  ) +
  scale_x_continuous(
    limits = c(extinction_time, extinction_time * 2.5),
    breaks = seq(extinction_time, extinction_time * 2.5,
      by = extinction_time / 2
    ),
    labels = function(x) {
      x - test_time
    },
    expand = expansion(mult = c(0.05, 0.1))
  ) +
  scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) +
  scale_colour_manual(values = c(
    "New" = "blue", "Best" = "green3", "Old" = "black")
  ) +
  scale_alpha_manual(values = c(
    "New" = 1, "Best" = 0.1, "Old" = 0.1)
  ) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(
    title = "C) Comparison",
    x = paste0(
      "Time to Achieve ", (1 - beta) * 100,
      "% Power\n(After Extinction)"
    ),
    y = "Average Type I Error Rate"
  )

all_plot <- ggarrange(extinct_plot, extant_plot, comparison_plot, ncol = 3)
ggsave("Figure2.svg", all_plot, width = 9, height = 3)
all_plot
```
