---
title: "Scenario B | Comparison"
format: 
  html:
    toc: true
    code-fold: true
    embed-resources: true
editor: visual
execute: 
  warning: false
lightbox: true  
---

# Setup

Load libraries:

```{r load-libraries}
library(tidyverse)
library(ggpubr)
```

Load in results from Extinct and Extant simulations:

```{r load-results}
best_models <- readRDS("Outputs/A/best_models.rds")

extinct_results <- readRDS("Outputs/B/Extinct/accuracy_results.rds") %>%
  mutate(best_model = model %in% best_models)
extant_results <- readRDS("Outputs/B/Extant/accuracy_results.rds") %>%
  mutate(best_model = model %in% best_models)
```

Re-specify relevant parameters used in simulations:

```{r parameters}
beta <- 0.2
```

# Comparison

```{r comparison}
#| fig-dpi: 600
#| fig-width: 12
#| fig-height: 4
extinct_plot <- ggplot() +
  geom_line(
    data = extinct_results,
    aes(x = extinction_time, y = threshold, group = model, colour = best_model),
    linewidth = 1,
    alpha = 0.1
  ) +
  geom_line(
    data = extinct_results %>%
      group_by(extinction_time) %>%
      summarise(threshold = mean(threshold, na.rm = TRUE)),
    aes(x = extinction_time, y = threshold),
    linewidth = 2
  ) +
  scale_y_continuous(limits = c(0, 150)) +
  scale_colour_manual(values = c("TRUE" = "green", "FALSE" = "black")) +
  theme_classic() +
  theme(
    legend.position = "none",
    strip.background = element_blank(),
    strip.text = element_text(family = "mono", face = "bold")
  ) +
  labs(
    title = "Extinct",
    x = paste0("Extinction Time"),
    y = paste0(
      "Estimated Time Offset Required for > ",
      (1 - beta) * 100, "% Power"
    )
  )

inst_plot <- ggplot() +
  geom_line(
    data = extant_results,
    aes(x = test_time, y = inst_error_rate, group = model, colour = best_model),
    linewidth = 1,
    alpha = 0.1
  ) +
  geom_line(
    data = extant_results %>%
      group_by(test_time) %>%
      summarise(inst_error_rate = mean(inst_error_rate, na.rm = TRUE)),
    aes(x = test_time, y = inst_error_rate),
    linewidth = 2
  ) +
  scale_y_continuous(limits = c(0, 1)) +
  scale_colour_manual(values = c("TRUE" = "green", "FALSE" = "black")) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(
    title = "Extant (Instantaneous)",
    x = paste0("Duration of Sighting Record"),
    y = "Observed Instantaneous Type I Error Rate"
  )

cum_plot <- ggplot() +
  geom_line(
    data = extant_results,
    aes(x = test_time, y = cum_error_rate, group = model, colour = best_model),
    linewidth = 1,
    alpha = 0.1
  ) +
  geom_line(
    data = extant_results %>%
      group_by(test_time) %>%
      summarise(cum_error_rate = mean(cum_error_rate, na.rm = TRUE)),
    aes(x = test_time, y = cum_error_rate),
    linewidth = 2
  ) +
  scale_y_continuous(limits = c(0, 1)) +
  scale_colour_manual(values = c("TRUE" = "green", "FALSE" = "black")) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(
    title = "Extant (Cumulative)",
    x = paste0("Duration of Sighting Record"),
    y = "Observed Cumulative Type I Error Rate"
  )

all_plot <- ggarrange(extinct_plot, inst_plot, cum_plot, ncol = 3)
all_plot
```

\
