---
title: "Scenario C | Comparison"
format: 
  html:
    toc: true
    code-fold: true
    embed-resources: true
editor: visual
execute: 
  warning: false
lightbox: true  
---

# Setup

Load libraries:

```{r load-libraries}
library(tidyverse)
library(scales)
library(ggpubr)
```

Load in results from simulations:

```{r load-results}
new_models <- c("BA26B1", "BA26B2", "BA26B3", "BA26B4")

best_models <- readRDS("Outputs/A/best_models.rds")

C1_initials <- readRDS("Outputs/C1/Extinct/initials.rds") %>%
  mutate(
    best_model = model %in% best_models,
    new_model = model %in% new_models
  )
C2_initials <- readRDS("Outputs/C2/Extinct/initials.rds") %>%
  mutate(
    best_model = model %in% best_models,
    new_model = model %in% new_models
  )
C3_initials <- readRDS("Outputs/C3/Extinct/initials.rds") %>%
  mutate(
    best_model = model %in% best_models,
    new_model = model %in% new_models
  )
C4_initials <- readRDS("Outputs/C4/Extinct/initials.rds") %>%
  mutate(
    best_model = model %in% best_models,
    new_model = model %in% new_models
  )

C1_thresholds <- readRDS("Outputs/C1/Extinct/thresholds.rds") %>%
  mutate(
    best_model = model %in% best_models,
    new_model = model %in% new_models
  )
C2_thresholds <- readRDS("Outputs/C2/Extinct/thresholds.rds") %>%
  mutate(
    best_model = model %in% best_models,
    new_model = model %in% new_models
  )
C3_thresholds <- readRDS("Outputs/C3/Extinct/thresholds.rds") %>%
  mutate(
    best_model = model %in% best_models,
    new_model = model %in% new_models
  )
C4_thresholds <- readRDS("Outputs/C4/Extinct/thresholds.rds") %>%
  mutate(
    best_model = model %in% best_models,
    new_model = model %in% new_models
  )

C1_extinct <- left_join(C1_initials, C1_thresholds, by = "model") %>%
  mutate(
    best_model = model %in% best_models,
    new_model = model %in% new_models
  )
C2_extinct <- left_join(C2_initials, C2_thresholds, by = "model") %>%
  mutate(
    best_model = model %in% best_models,
    new_model = model %in% new_models
  )
C3_extinct <- left_join(C3_initials, C3_thresholds, by = "model") %>%
  mutate(
    best_model = model %in% best_models,
    new_model = model %in% new_models
  )
C4_extinct <- left_join(C4_initials, C4_thresholds, by = "model") %>%
  mutate(
    best_model = model %in% best_models,
    new_model = model %in% new_models
  )
```

# Extinct Comparison

Compare C1 with C2, C3, and C4:

```{r extinct-comparison}
#| fig-dpi: 600
#| fig-width: 9
#| fig-height: 9

max_threshold <- 250

C1_extinct <- C1_extinct %>%
  mutate(oob = threshold >= max_threshold)

C2_joined <- left_join(
  C1_extinct,
  C2_extinct,
  by = c("model", "best_model", "new_model"),
  suffix = c("_C1", "_C2")
) %>%
  mutate(oob = threshold_C2 >= max_threshold)

C3_joined <- left_join(
  C1_extinct,
  C3_extinct,
  by = c("model", "best_model", "new_model"),
  suffix = c("_C1", "_C3")
) %>%
  mutate(oob = threshold_C3 >= max_threshold)

C4_joined <- left_join(
  C1_extinct,
  C4_extinct,
  by = c("model", "best_model", "new_model"),
  suffix = c("_C1", "_C4")
) %>%
  mutate(oob = threshold_C4 >= max_threshold)

C1_plot <- ggplot(C1_extinct) +
  geom_point(
    aes(
      x = power, y = threshold, shape = oob,
      colour = best_model, alpha = new_model
    ),
    size = 2
  ) +
  scale_x_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) +
  scale_y_continuous(limits = c(0, max_threshold), oob = squish) +
  scale_shape_manual(values = c("TRUE" = 17, "FALSE" = 16)) +
  scale_colour_manual(values = c("TRUE" = "green3", "FALSE" = "black")) +
  scale_alpha_manual(values = c("TRUE" = 1, "FALSE" = 0.1)) +
  labs(
    x = "Initial Power at Extinction",
    y = "Time to Achieve 80% Power",
    title = "A) Null"
  ) +
  theme_classic() +
  theme(legend.position = "none")

C2_plot <- ggplot(C2_joined) +
  geom_segment(
    aes(x = power_C1, y = threshold_C1, xend = power_C2, yend = threshold_C2),
    colour = "grey",
    linewidth = 0.25
  ) +
  geom_point(
    aes(x = power_C1, y = threshold_C1),
    colour = "grey",
    size = 1
  ) +
  geom_point(
    aes(
      x = power_C2, y = threshold_C2, shape = oob,
      colour = best_model, alpha = new_model
    ),
    size = 2
  ) +
  scale_x_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) +
  scale_y_continuous(limits = c(0, max_threshold), oob = squish) +
  scale_shape_manual(values = c("TRUE" = 17, "FALSE" = 16)) +
  scale_colour_manual(values = c("TRUE" = "green3", "FALSE" = "black")) +
  scale_alpha_manual(values = c("TRUE" = 1, "FALSE" = 0.1)) +
  labs(
    x = "Initial Power at Extinction",
    y = "Time to Achieve 80% Power",
    title = "B) Declining Detectability"
  ) +
  theme_classic() +
  theme(legend.position = "none")

C3_plot <- ggplot(C3_joined) +
  geom_segment(
    aes(x = power_C1, y = threshold_C1, xend = power_C3, yend = threshold_C3),
    colour = "grey",
    linewidth = 0.25
  ) +
  geom_point(
    aes(x = power_C1, y = threshold_C1),
    colour = "grey",
    size = 1
  ) +
  geom_point(
    aes(
      x = power_C3, y = threshold_C3, shape = oob,
      colour = best_model, alpha = new_model
    ),
    size = 2
  ) +
  scale_x_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) +
  scale_y_continuous(limits = c(0, max_threshold), oob = squish) +
  scale_shape_manual(values = c("TRUE" = 17, "FALSE" = 16)) +
  scale_colour_manual(values = c("TRUE" = "green3", "FALSE" = "black")) +
  scale_alpha_manual(values = c("TRUE" = 1, "FALSE" = 0.1)) +
  labs(
    x = "Initial Power at Extinction",
    y = "Time to Achieve 80% Power",
    title = "C) Increasing Survey Effort"
  ) +
  theme_classic() +
  theme(legend.position = "none")

C4_plot <- ggplot(C4_joined) +
  geom_segment(
    aes(x = power_C1, y = threshold_C1, xend = power_C4, yend = threshold_C4),
    colour = "grey",
    linewidth = 0.25
  ) +
  geom_point(
    aes(x = power_C1, y = threshold_C1),
    colour = "grey",
    size = 1
  ) +
  geom_point(
    aes(
      x = power_C4, y = threshold_C4, shape = oob,
      colour = best_model, alpha = new_model
    ),
    size = 2
  ) +
  scale_x_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) +
  scale_y_continuous(limits = c(0, max_threshold), oob = squish) +
  scale_shape_manual(values = c("TRUE" = 17, "FALSE" = 16)) +
  scale_colour_manual(values = c("TRUE" = "green3", "FALSE" = "black")) +
  scale_alpha_manual(values = c("TRUE" = 1, "FALSE" = 0.1)) +
  labs(
    x = "Initial Power at Extinction",
    y = "Time to Achieve 80% Power",
    title = "D) Combined"
  ) +
  theme_classic() +
  theme(legend.position = "none")

all_plot <- ggarrange(C1_plot, C2_plot, C3_plot, C4_plot, ncol = 2, nrow = 2)
ggsave("Figure4.svg", all_plot, width = 9, height = 9)
all_plot
```

# Illustrative Figure

Read in figures from subscenarios:

```{r load-figures}
C1_plot <- readRDS("Outputs/C1/Extinct/C1_sighting_rates.rds")
C2_plot <- readRDS("Outputs/C2/Extinct/C2_sighting_rates.rds")
C3_plot <- readRDS("Outputs/C3/Extinct/C3_sighting_rates.rds")
C4_plot <- readRDS("Outputs/C4/Extinct/C4_sighting_rates.rds")
```

Combine and plot:

```{r illustrative-figure}
#| fig-dpi: 600
#| fig-width: 8
#| fig-height: 8
C_plot <- ggarrange(C1_plot, C2_plot, C3_plot, C4_plot, nrow = 4)
C_plot
ggsave("FigureS2.svg", C_plot, width = 8, height = 8)
```
