---
title: "Scenario D | Comparison"
format: 
  html:
    toc: true
    code-fold: true
    embed-resources: true
editor: visual
execute: 
  warning: false
lightbox: true  
---

# Setup

Load libraries:

```{r load-libraries}
library(tidyverse)
library(ggpubr)
```

Load in results from simulations:

```{r load-results}
best_models <- readRDS("Outputs/A/best_models.rds")

D1_power_summary <- readRDS("Outputs/D1/Extinct/power_summary.rds") %>%
  mutate(best_model = model %in% best_models)
D2_power_summary <- readRDS("Outputs/D2/Extinct/power_summary.rds") %>%
  mutate(best_model = model %in% best_models)
D3_power_summary <- readRDS("Outputs/D3/Extinct/power_summary.rds") %>%
  mutate(best_model = model %in% best_models)
D4_power_summary <- readRDS("Outputs/D4/Extinct/power_summary.rds") %>%
  mutate(best_model = model %in% best_models)
```

# Extinct Comparison

Compare D1 with D2, D3, and D4:

```{r extinct-comparison}
#| fig-dpi: 600
#| fig-width: 9
#| fig-height: 9
D2_joined <- left_join(
  D1_power_summary,
  D2_power_summary,
  by = c("model", "best_model"),
  suffix = c("_D1", "_D2")
)

D3_joined <- left_join(
  D1_power_summary,
  D3_power_summary,
  by = c("model", "best_model"),
  suffix = c("_D1", "_D3")
)

D4_joined <- left_join(
  D1_power_summary,
  D4_power_summary,
  by = c("model", "best_model"),
  suffix = c("_D1", "_D4")
)

D1_plot <- ggplot(D1_power_summary) +
  geom_point(
    aes(x = early, y = later, colour = best_model),
    size = 2
  ) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  scale_x_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) +
  scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) +
  scale_colour_manual(values = c("TRUE" = "green3", "FALSE" = "black")) +
  labs(
    x = "Power Early After Extinction",
    y = "Power Later After Extinction",
    title = "A) Null"
  ) +
  theme_classic() +
  theme(legend.position = "none")

D2_plot <- ggplot(D2_joined) +
  geom_segment(
    aes(x = early_D1, y = later_D1, xend = early_D2, yend = later_D2),
    colour = "grey",
    linewidth = 0.25
  ) +
  geom_point(
    aes(x = early_D1, y = later_D1),
    colour = "grey",
    size = 1
  ) +
  geom_point(
    aes(x = early_D2, y = later_D2, colour = best_model),
    size = 2
  ) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  scale_x_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) +
  scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) +
  scale_colour_manual(values = c("TRUE" = "green3", "FALSE" = "black")) +
  labs(
    x = "Power Early After Extinction",
    y = "Power Later After Extinction",
    title = "B) Matched"
  ) +
  theme_classic() +
  theme(legend.position = "none")

D3_plot <- ggplot(D3_joined) +
  geom_segment(
    aes(x = early_D1, y = later_D1, xend = early_D3, yend = later_D3),
    colour = "grey",
    linewidth = 0.25
  ) +
  geom_point(
    aes(x = early_D1, y = later_D1),
    colour = "grey",
    size = 1
  ) +
  geom_point(
    aes(x = early_D3, y = later_D3, colour = best_model),
    size = 2
  ) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  scale_x_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) +
  scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) +
  scale_colour_manual(values = c("TRUE" = "green3", "FALSE" = "black")) +
  labs(
    x = "Power Early After Extinction",
    y = "Power Later After Extinction",
    title = "C) Constant"
  ) +
  theme_classic() +
  theme(legend.position = "none")

D4_plot <- ggplot(D4_joined) +
  geom_segment(
    aes(x = early_D1, y = later_D1, xend = early_D4, yend = later_D4),
    colour = "grey",
    linewidth = 0.25
  ) +
  geom_point(
    aes(x = early_D1, y = later_D1),
    colour = "grey",
    size = 1
  ) +
  geom_point(
    aes(x = early_D4, y = later_D4, colour = best_model),
    size = 2
  ) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  scale_x_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) +
  scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) +
  scale_colour_manual(values = c("TRUE" = "green3", "FALSE" = "black")) +
  labs(
    x = "Power Early After Extinction",
    y = "Power Later After Extinction",
    title = "D) Increasing"
  ) +
  theme_classic() +
  theme(legend.position = "none")

all_plot <- ggarrange(D1_plot, D2_plot, D3_plot, D4_plot, ncol = 2, nrow = 2)
ggsave("Figure5.svg", all_plot, width = 9, height = 9)
all_plot
```

# Illustrative Figures

Plot sighting rates:

```{r sighting-rate-plot}
#| fig-dpi: 600
#| fig-width: 8
#| fig-height: 2
extinction_time <- 100
max_test_time <- 200

eps <- 0.5
p_i <- 0.7
p_r <- 0.5

pse <- eps * p_i * p_r

D1_rates <- tibble(
  scenario = "Null",
  time = seq(0, max_test_time, by = 1),
  c_rate = c(
    rep(pse, extinction_time + 1),
    rep(0, max_test_time - extinction_time)
  ),
  u_rate = c(
    rep(0, extinction_time + 1),
    rep(0, max_test_time - extinction_time)
  )
)

D2_rates <- tibble(
  scenario = "Matched",
  time = seq(0, max_test_time, by = 1),
  c_rate = c(
    rep(pse, extinction_time + 1),
    rep(0, max_test_time - extinction_time)
  ),
  u_rate = c(
    rep(pse, extinction_time + 1),
    rep(0, max_test_time - extinction_time)
  )
)

D3_rates <- tibble(
  scenario = "Constant",
  time = seq(0, max_test_time, by = 1),
  c_rate = c(
    rep(pse, extinction_time + 1),
    rep(0, max_test_time - extinction_time)
  ),
  u_rate = rep(pse, max_test_time + 1)
)

D4_rates <- tibble(
  scenario = "Increasing",
  time = seq(0, max_test_time, by = 1),
  c_rate = c(
    rep(pse, extinction_time + 1),
    rep(0, max_test_time - extinction_time)
  ),
  u_rate = pse * (0:max_test_time) / extinction_time
)

sighting_rates <- bind_rows(D1_rates, D2_rates, D3_rates, D4_rates) %>%
  mutate(scenario = factor(scenario, levels = c("Null", "Matched", "Constant", "Increasing")))

D_plot <- ggplot(sighting_rates) +
  geom_step(
    aes(x = time, y = u_rate),
    colour = "darkred", linewidth = 1
  ) +
  geom_step(
    aes(x = time, y = c_rate),
    colour = "darkblue", linetype = "11", linewidth = 1
  ) +
  geom_vline(xintercept = extinction_time, linetype = "dashed") +
  scale_x_continuous(
    limits = c(0, max_test_time),
    breaks = c(0, extinction_time, max_test_time),
    name = "Time"
  ) +
  scale_y_continuous(
    limits = c(0, 1),
    breaks = c(0, 0.5, 1),
    name = "Sighting Rate"
  ) +
  facet_wrap(~scenario, ncol = 4, nrow = 1, axes = "all") +
  theme_classic() +
  theme(
    strip.background = element_blank(),
    strip.text = element_text(hjust = 0, size = rel(1.2)),
    panel.spacing = unit(1.0, "lines")
  )

D_plot
ggsave("FigureS3.svg", D_plot, width = 8, height = 2)
```

Plot sighting uncertainty distributions:

```{r certainty-plot}
#| fig-dpi: 600
#| fig-width: 8
#| fig-height: 4
rtruncbeta <- function(n, shape1, shape2, min = 0, max = 1) {
  u <- runif(n, pbeta(min, shape1, shape2), pbeta(max, shape1, shape2))
  return(qbeta(u, shape1, shape2))
}

c_sample <- rtruncbeta(1e6, 2, 3, 0, 0.9)
u_sample <- rtruncbeta(1e6, 25, 1, 0.9, 1)

certainty_plot <- ggplot() +
  geom_histogram(
    aes(x = c_sample, y = after_stat(density)),
    binwidth = 0.01,
    fill = "darkred",
    boundary = 0
  ) +
  geom_histogram(
    aes(x = u_sample, y = after_stat(density)),
    binwidth = 0.01,
    fill = "darkblue",
    boundary = 1
  ) +
  labs(x = "Certainty Score", y = "Density") +
  theme_classic()

certainty_plot
ggsave("FigureS4.svg", certainty_plot, width = 8, height = 4)
```
